name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 22 * * 0"  # Sunday 22:00 UTC = Monday 06:00 PHT
    - cron: "0 4 * * 5"   # Friday 04:00 UTC = Friday 12:00 PHT
  workflow_dispatch:      # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/workcontrolgit/TalentManagementNet9.git
          git fetch upstream master

      - name: Merge upstream master
        run: |
          git checkout master
          git merge upstream/master --no-edit

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} master
